### ISSUE TITLE
[Bug] Issues with space in path on secondary disk drives. 

### ISSUE THREAD

**Issue by Jamie96ITS** [sop/wslscript#1]
Hello!

I seem to have run into an issue with WSLScript supporting spaces in filenames when called from a secondary disk drive, like B:\ or D:\ .

If I take the bash-test.sh from the repo, and drag the test file on it from anywhere on the C:\ drive, I get, as expected, this:

```
Current directory: /mnt/c/temp/examples
Path to this script: ./bash-test.sh
Argument #1: /mnt/c/temp/examples/Drag 'me!'
  File: /mnt/c/temp/examples/Drag 'me!'
  Size: 89              Blocks: 0          IO Block: 512    regular file
Device: fh/15d  Inode: 31525197391853963  Links: 1
Access: (0777/-rwxrwxrwx)  Uid: ( 1000/   jamie)   Gid: ( 1000/   jamie)
Access: 2022-02-05 09:17:00.175892100 -0500
Modify: 2021-08-27 08:27:41.000000000 -0400
Change: 2022-02-05 09:06:42.403934500 -0500
 Birth: -

[Process exited - exit code 1]
```
![image](https://user-images.githubusercontent.com/26676527/152645655-0c4d8894-5cdd-47dd-b30f-af9fe8d628ef.png)

However, try this same test on another drive:

```
Current directory: /mnt/b/temp/examples
Path to this script: ./bash-test.sh
Argument #1: /mnt/b/temp/examples/Drag
Argument #2: 'me!'

[Process exited - exit code 1]

```
![image](https://user-images.githubusercontent.com/26676527/152645636-2ca585f1-aa4a-4ec6-bed5-a3dfb6bd7a86.png)

Or another:
```
Current directory: /mnt/d
Path to this script: ./bash-test.sh
Argument #1: /mnt/d/Drag
Argument #2: 'me!'

[Process exited - exit code 1]
```
![image](https://user-images.githubusercontent.com/26676527/152645614-1238cf4e-e78b-4700-ac1c-b477d6aee871.png)

And if I drop the space it works as intended. 
```
Current directory: /mnt/d
Path to this script: ./bash-test.sh
Argument #1: /mnt/d/Drag'me!'
  File: /mnt/d/Drag'me!'
  Size: 89              Blocks: 0          IO Block: 4096   regular file
Device: 10h/16d Inode: 6192449488251590  Links: 1
Access: (0777/-rwxrwxrwx)  Uid: ( 1000/   jamie)   Gid: ( 1000/   jamie)
Access: 2022-02-05 09:12:58.517840800 -0500
Modify: 2021-08-27 08:27:41.000000000 -0400
Change: 2022-02-05 09:24:06.866490700 -0500
 Birth: -

[Process exited - exit code 1]
```
![image](https://user-images.githubusercontent.com/26676527/152645777-727b90c6-ce60-4d10-9b94-933f098fb5ec.png)

**Comment by sop** [comment]
Hi!

Thanks for the report. I've managed to reproduce it. The problem is actually in the Windows drop handler and i think it has to do with long filename support on different drives, i'm not sure, it's a mess :S. On my computer the whitespace splitting occurs on 3 drives (D, E and F) but works properly on 2 (C and G). I haven't been able to figure out why though.

I'm afraid there's no easy fix at the moment, but i keep evaluating some options.

**Comment by sop** [comment]
This issue should now be fixed as i implemented drag & drop as a proper shell extension. Please try [0.7.0-rc.1](https://github.com/sop/wslscript/releases/tag/0.7.0-rc.1) release to see whether your problem still persists.
Also note that you have to register the file name extension again. This is simply performed by opening the GUI from `wslscript.exe`, double clicking your existing filetype and clicking _Save_.

**Comment by Jamie96ITS** [comment]
This has solved the issue.

Examples from the repo are working as expected. I'll try it with more stuff another time but I expect this is handled. 

Thanks!

**Comment by sop** [comment]
Glad to hear the issue is resolved! I've also published a [production release](https://github.com/sop/wslscript/releases/tag/0.7.0) with some additional features.
